### ISSUE TITLE
Add Manet Lunch

### ISSUE THREAD

**Issue by DotRat617** [superducktoes/bostondives#8]
{
    "name": "Manet Lunch",
    "location": "42.2677379, -70.9565909",
    "whatToOrder": "PBR, Yuengling or Pizza",
    "type": "bar",
    "hours": {
      "0": [
        "08:00,01:00"
      ],
      "1": [
        "08:00,01:00"
      ],
      "2": [
        "08:00,01:00"
      ],
      "3": [
        "08:00,01:00"
      ],
      "4": [
        "08:00,01:00"
      ],
      "5": [
        "08:00,01:00"
      ],
      "6": [
        "08:00,01:00"
      ]
    },
    "website": "https://www.facebook.com/pages/Manet-Lunch/120178907993890"
  },

**Comment by DotRat617** [comment]
Love your map!

**Comment by superducktoes** [comment]
thanks @DotRat617 added to the map!
